<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SiddhiRao-FVFGWQ7VQ05D" failures="1" tests="1" name="BStackDemo 4-1" time="30.158" errors="0" timestamp="2024-05-23T17:01:05 IST">
  <testcase classname="com.browserstack.test.suites.offers.OfferTest" name="checkOffersInSingapore" time="1.811">
    <failure type="java.lang.AssertionError" message="expected [3] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [0]
at com.browserstack.test.suites.offers.OfferTest.checkOffersInSingapore(OfferTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- checkOffersInSingapore -->
</testsuite> <!-- BStackDemo 4-1 -->
